### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by vikasTmz** [vikasTmz/DeepTexture#1]
- [x]  GCP : group project + get access to better GPUs
- [x] Visualize TextureFields results: Find out what's good and bad about their results.
- [x] Write up and submit Check in 2
- [x] Email Eliot to set up next meeting/start email chain
- [ ] Understand TextureFields code (which files contain what will be a helpful start).
- [ ] Setup DeepSDF : get pre-trained ShapeNet weights / train it on 3D Future.
- [ ] Preprocess 3D Future to match ShapeNet's data format.

**Comment by vikasTmz** [comment]
Possible paths:
- [ ] Use a pre-trained PointNet encoder (on cars) from the occupancy network paper instead of training the PointNet encoder from scratch. 
     - Experiments will be done on ShapeNet cars.
- [ ] Replace/ append another loss instead of just l1 (L_conditional). 
    - Experiments can be done on either dataset.
    - Try using a perceptual loss maybe?

- [ ] Condition the discriminator in the cGAN setup with more inputs (than just depth). Maybe part-level segmentation?
- [ ] Use a pre-trained DeepSDF model:
     - If it is pre-trained on cars, then this should take the same route as point 1.
     - If it is pre-trained on chairs, then we have to devise a new set of experiments with 3D Future.
- [x] Substitute Pointnet encoder for Pointnet++ encoder
- [ ] Export the predicted colors along with the point coordinates. .ply is an ideal format.
